from config import SEMANTIC_SCHOLAR_CITATIONS_DATASET_NAME
from data_retrival.neo4j.citations import CitationBatchProcessor
from data_retrival.semantic_scholar.download_dataset_handler import DatasetHandler

database_handler = DatasetHandler(SEMANTIC_SCHOLAR_CITATIONS_DATASET_NAME)
next_citations_dataset_link = database_handler.download_dataset_handler.get_next_url_to_download()
# authorized_citations_url = database_handler.get_authorized_url(next_citations_dataset_link)
# file_path = database_handler.handle_url_download(authorized_citations_url)
file_path = r"files\citations_dataset\20241115_081922_00277_4pq6k_04f68738-4009-48e5-abfc-0253ad2b8a25"
citations_batch_processor = CitationBatchProcessor()
citations_batch_processor.process_json(file_path)
citations_batch_processor.close()
database_handler.download_dataset_handler.mark_url_as_downloaded(next_citations_dataset_link)